name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: ["1.20"]

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: go test -v -race ./...
